train_src: ../data/ds/enhi/train.hi.tok
train_tgt: ../data/ds/enhi/train.en.tok
valid_src: ../data/ds/enhi/dev.hi.tok
valid_tgt: ../data/ds/enhi/dev.en.tok
truncate: True
src_len: 512
tgt_len: 512
shared: False
# max_types: 4000
max_src_types: 8000
max_tgt_types: 8000
pieces: skipgram
# ngram_sorter: naive_pmi
# include_ngrams:
#   - 2
#   - 3
# max_ngrams: 400
skipgram_sorter: skip_pmi
include_skipgrams: 
  - 0 1
  - 0 2
  # - 2 1 # Second parameter is for how many tokens are to be skipped
max_skipgrams: 200
min_freq: 100
min_instances: 15
max_instance_probs: 0.1
