train_src: ../data/hi-en/train.hin.tok
train_tgt: ../data/hi-en/train.eng.tok
valid_src: ../data/hi-en/tests/IITB-hien_dev-3.hin.tok
valid_tgt: ../data/hi-en/tests/IITB-hien_dev-3.eng.tok
truncate: True
src_len: 512
tgt_len: 512
shared: False
# max_types: 4000
max_src_types: 4000
max_tgt_types: 4000
pieces: skipgram
min_freq: 100
# ngram_sorter: naive_pmi
# include_ngrams:
#   - 2
#   - 3
# max_ngrams: 400
skipgram_sorter: skip_pmi
include_skipgrams: 
  - 2 1
max_skipgrams: 400
min_instances: 15
max_instance_probs: 0.1
