train_src: ../data/de-en/train.deu.tok
train_tgt: ../data/de-en/train.eng.tok
valid_src: ../data/de-en/tests/newstest2018.deu.tok
valid_tgt: ../data/de-en/tests/newstest2018.eng.tok
truncate: True
src_len: 512
tgt_len: 512
shared: True
max_types: 4000
# max_src_types: 4000
# max_tgt_types: 4000
pieces: skipgram
min_freq: 100
# ngram_sorter: naive_pmi
# include_ngrams:
#   - 2
#   - 3
# max_ngrams: 400
skipgram_sorter: freq
include_skipgrams: 
  - 2 3
  - 2 1
max_skipgrams: 400
min_instances: 15
max_instance_probs: 0.1
